//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public System.Guid Id { get; set; }
        public int Order_Number { get; set; }
        public System.Guid ProductId { get; set; }
        public int Number { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Sum { get; set; }
        public System.DateTime Date { get; set; }
    }
}
